#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow>=10", "resvg-py>=0.2"]
# ///
"""Convert the icons named in bedlift/assets/icons/icons.txt into 8-bit
coverage maps.

SVG sources are rendered directly at the target size (resvg), so strokes and
edges are anti-aliased for that exact pixel grid. PNGs are downsampled.

    uv run gen_icons.py <icons_dir> <out.cpp>

Output is a C++ source defining ui_icon_table[] / ui_icon_count (see
include/ui_icons.hpp). Invoked by the build via icons.cmake; can also be run
by hand to inspect the result.
"""

import io
import sys
from pathlib import Path

import resvg_py
from PIL import Image


def parse_manifest(path: Path):
    icons = []
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) not in (2, 3):
            sys.exit(f"{path}:{lineno}: expected '<name> <size> [source.png]'")
        name, size = parts[0], int(parts[1])
        src = parts[2] if len(parts) == 3 else None
        if not 1 <= size <= 255:
            sys.exit(f"{path}:{lineno}: size {size} out of range 1..255")
        icons.append((name, size, src, lineno))
    return icons


def resolve_source(icons_dir: Path, name: str, src: str | None) -> Path:
    if src:
        return icons_dir / src
    for ext in (".svg", ".png"):
        if (icons_dir / f"{name}{ext}").is_file():
            return icons_dir / f"{name}{ext}"
    return icons_dir / f"{name}.svg"            # reported as missing


def fit(w: int, h: int, size: int) -> tuple[int, int]:
    s = size / max(w, h)
    return max(1, round(w * s)), max(1, round(h * s))


def svg_render(svg: Path, **kw) -> Image.Image:
    png = resvg_py.svg_to_bytes(svg_path=str(svg), skip_system_fonts=True, **kw)
    return Image.open(io.BytesIO(bytes(png))).convert("RGBA")


def coverage(src: Path, size: int) -> Image.Image:
    if src.suffix.lower() == ".svg":
        # native render only to learn the aspect ratio, then the real one
        tw, th = fit(*svg_render(src).size, size)
        return svg_render(src, width=tw, height=th).getchannel("A")

    img = Image.open(src)
    if img.mode in ("RGBA", "LA") or "transparency" in img.info:
        a = img.convert("RGBA").getchannel("A")
    else:
        # opaque art: dark ink on a light ground
        a = Image.eval(img.convert("L"), lambda v: 255 - v)
    return a.resize(fit(*a.size, size), Image.Resampling.LANCZOS)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    icons_dir, out = Path(sys.argv[1]), Path(sys.argv[2])
    manifest = icons_dir / "icons.txt"
    icons = parse_manifest(manifest)

    seen = set()
    lines = [
        "// GENERATED by components/ui/scripts/gen_icons.py from assets/icons/icons.txt",
        "// — do not edit.",
        '#include "ui_icons.hpp"',
        "",
    ]
    entries = []
    for i, (name, size, src, lineno) in enumerate(icons):
        if name in seen:
            sys.exit(f"{manifest}:{lineno}: duplicate icon name '{name}'")
        seen.add(name)
        path = resolve_source(icons_dir, name, src)
        if not path.is_file():
            sys.exit(f"{manifest}:{lineno}: missing {path}")
        a = coverage(path, size)
        w, h = a.size
        data = a.tobytes()
        lines.append(f"// {name}: {path.name} -> {w}x{h}")
        lines.append(f"static const uint8_t k_icon_{i}[{w * h}] = {{")
        for r in range(h):
            row = data[r * w:(r + 1) * w]
            lines.append("    " + ",".join(str(v) for v in row) + ",")
        lines.append("};")
        entries.append(f'    {{ "{name}", {w}, {h}, k_icon_{i} }},')

    lines.append("")
    lines.append("const ui_icon_t ui_icon_table[] = {")
    lines += entries
    lines.append("};")
    lines.append(f"const int ui_icon_count = {len(entries)};")

    text = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    # leave the file alone when nothing changed so the build stays incremental
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    print(f"gen_icons: {len(entries)} icons -> {out}")


if __name__ == "__main__":
    main()
