#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow>=10"]
# ///
"""Convert the PNGs named in icons/icons.txt into 8-bit coverage maps.

    uv run gen_icons.py <icons_dir> <out.cpp>

Output is a C++ source defining ui_icon_table[] / ui_icon_count (see
include/ui_icons.hpp). Invoked by the build via icons.cmake; can also be run
by hand to inspect the result.
"""

import sys
from pathlib import Path

from PIL import Image


def parse_manifest(path: Path):
    icons = []
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) not in (2, 3):
            sys.exit(f"{path}:{lineno}: expected '<name> <size> [source.png]'")
        name, size = parts[0], int(parts[1])
        src = parts[2] if len(parts) == 3 else f"{name}.png"
        if not 1 <= size <= 255:
            sys.exit(f"{path}:{lineno}: size {size} out of range 1..255")
        icons.append((name, size, src, lineno))
    return icons


def coverage(png: Path, size: int) -> Image.Image:
    img = Image.open(png)
    if img.mode in ("RGBA", "LA") or "transparency" in img.info:
        a = img.convert("RGBA").getchannel("A")
    else:
        # opaque art: dark ink on a light ground
        a = Image.eval(img.convert("L"), lambda v: 255 - v)
    w, h = a.size
    s = size / max(w, h)
    tw, th = max(1, round(w * s)), max(1, round(h * s))
    return a.resize((tw, th), Image.Resampling.LANCZOS)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    icons_dir, out = Path(sys.argv[1]), Path(sys.argv[2])
    manifest = icons_dir / "icons.txt"
    icons = parse_manifest(manifest)

    seen = set()
    lines = [
        "// GENERATED by components/ui/scripts/gen_icons.py from icons/icons.txt",
        "// — do not edit.",
        '#include "ui_icons.hpp"',
        "",
    ]
    entries = []
    for i, (name, size, src, lineno) in enumerate(icons):
        if name in seen:
            sys.exit(f"{manifest}:{lineno}: duplicate icon name '{name}'")
        seen.add(name)
        png = icons_dir / src
        if not png.is_file():
            sys.exit(f"{manifest}:{lineno}: missing {png}")
        a = coverage(png, size)
        w, h = a.size
        data = a.tobytes()
        lines.append(f"// {name}: {src} -> {w}x{h}")
        lines.append(f"static const uint8_t k_icon_{i}[{w * h}] = {{")
        for r in range(h):
            row = data[r * w:(r + 1) * w]
            lines.append("    " + ",".join(str(v) for v in row) + ",")
        lines.append("};")
        entries.append(f'    {{ "{name}", {w}, {h}, k_icon_{i} }},')

    lines.append("")
    lines.append("const ui_icon_t ui_icon_table[] = {")
    lines += entries
    lines.append("};")
    lines.append(f"const int ui_icon_count = {len(entries)};")

    text = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    # leave the file alone when nothing changed so the build stays incremental
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    print(f"gen_icons: {len(entries)} icons -> {out}")


if __name__ == "__main__":
    main()
